#r "../packages/EventStore.Client/lib/net40/EventStore.ClientAPI.dll"
#r "../packages/FSharp.Control.AsyncSeq/lib/net45/FSharp.Control.AsyncSeq.dll"
#r "../packages/FSharp.Data/lib/portable-net45+netcore45/FSharp.Data.DesignTime.dll"
#r "../packages/FSharp.Data/lib/portable-net45+netcore45/FSharp.Data.dll"
#r "bin/Release/Micromachine.dll"
#r "bin/Release/Survey.dll"
